import { Check, ClipboardCheck, Handshake, Play, Target } from "lucide-react";
import { WordPullUp } from "@/components/WordPullUp";
import { CtaBand, imagePath, PageHero, SiteShell, TrustStrip } from "@/components/SiteShell";

const videos = [
  { file: "zaki-01.mp4", label: "01", eyebrow: "Organisation", title: "Une équipe présente, du premier passage à la finition.", text: "Chaque intervention commence par une lecture claire des lieux. Nous préparons les zones, le matériel et l'ordre de nettoyage pour garder un résultat propre et régulier." },
  { file: "zaki-02.mp4", label: "02", eyebrow: "Méthode", title: "Le bon geste et le bon équipement pour chaque surface.", text: "Sols, vitres, mobilier, sanitaires ou zones de circulation : la méthode est choisie selon les matériaux et le niveau de propreté attendu." },
  { file: "zaki-03.mp4", label: "03", eyebrow: "Exigence", title: "Une intervention nette dans les espaces qui comptent.", text: "Nous travaillons avec discrétion et précision dans les maisons, administrations, écoles, cliniques et sites professionnels." },
  { file: "zaki-04.mp4", label: "04", eyebrow: "Suivi", title: "Un contrôle final avant de remettre les lieux.", text: "La prestation se termine par une vérification des points essentiels afin de vous laisser un espace prêt à vivre, à accueillir ou à travailler." },
];

export default function AboutPage() {
  return (
    <SiteShell>
      <PageHero eyebrow="À propos de Zaki Cleaning" title="Une exigence de propreté pour tous les espaces." text="Nous accompagnons particuliers, entreprises et collectivités avec des prestations organisées, du ponctuel au quotidien." image="factory.png" />
      <TrustStrip />
      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2 lg:items-center"><img src={imagePath("administration.png")} alt="Nettoyage professionnel dans un espace administratif" className="h-[520px] w-full rounded-lg object-cover" /><div><p className="section-kicker">Notre métier</p><h2 className="section-title">Faire de chaque lieu un espace net et accueillant.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Zaki Cleaning assure le nettoyage de fin de chantier, maisons habitées, villas, usines, administrations, écoles, cliniques et espaces commerciaux.</p><p className="mt-5 text-base leading-7 text-slate-600">Notre approche est simple : comprendre vos besoins, organiser l'intervention, utiliser le matériel approprié et contrôler la qualité avant notre départ.</p><ul className="mt-8 space-y-4">{["Un devis défini selon votre lieu", "Une prestation ponctuelle ou régulière", "Des produits adaptés aux surfaces", "Un contrôle final de la qualité"].map((item) => <li key={item} className="flex gap-3 text-sm font-extrabold text-slate-800"><Check className="h-5 w-5 text-sky-600" />{item}</li>)}</ul></div></div></section>
      <section className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="section-kicker">En images</p><WordPullUp words="Nos interventions sur le terrain." className="mt-4 text-3xl font-extrabold leading-tight text-slate-950 sm:text-5xl" /></div><div className="mt-14 space-y-16 lg:space-y-24">{videos.map((video, index) => <article key={video.file} className="grid gap-8 lg:grid-cols-2 lg:items-center lg:gap-16"><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="overflow-hidden rounded-lg bg-slate-200 shadow-[0_18px_48px_rgba(7,21,33,0.14)]"><video controls preload="metadata" playsInline className="block h-[360px] w-full object-cover sm:h-[460px]"><source src={`${import.meta.env.BASE_URL}videos/zaki/${video.file}`} type="video/mp4" />Votre navigateur ne prend pas en charge cette vidéo.</video></div></div><div className={index % 2 === 1 ? "lg:order-1" : ""}><div className="flex items-center gap-3 text-xs font-extrabold uppercase text-sky-600"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-sky-100 text-[#071521]">{video.label}</span>{video.eyebrow}</div><WordPullUp words={video.title} className="mt-6 text-3xl font-extrabold leading-tight text-slate-950 sm:text-4xl" /><p className="mt-6 max-w-xl text-base leading-8 text-slate-600">{video.text}</p><div className="mt-7 flex items-center gap-3 text-sm font-extrabold text-slate-800"><Play className="h-4 w-4 text-sky-600" />Zaki Cleaning en intervention</div></div></article>)}</div></div></section>
      <section className="bg-[#071521] px-5 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3">{[{ icon: Target, title: "Précision", text: "Nous avançons zone par zone pour garder une qualité régulière." }, { icon: Handshake, title: "Clarté", text: "Le périmètre et les priorités sont définis avant l'intervention." }, { icon: ClipboardCheck, title: "Contrôle", text: "Le résultat final est vérifié avant la fin de la prestation." }].map(({ icon: Icon, title, text }) => <div key={title} className="border-t border-sky-400 pt-6"><Icon className="h-7 w-7 text-sky-300" /><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{text}</p></div>)}</div></section>
      <CtaBand />
    </SiteShell>
  );
}
