import { ArrowRight, CalendarDays, CheckCircle2, ClipboardCheck, Cross, Factory, HardHat, Home, Landmark, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { WordPullUp } from "@/components/WordPullUp";
import { CtaBand, imagePath, PageHero, SiteShell, TrustStrip } from "@/components/SiteShell";

const services = [
  { icon: HardHat, image: "end-of-construction.png", title: "Fin de chantier", text: "Remise en état complète après travaux, prête à être livrée." },
  { icon: Home, image: "house-occupied.png", title: "Maisons habitées", text: "Grand nettoyage et entretien précis de votre logement." },
  { icon: Factory, image: "factory.png", title: "Usines & sites", text: "Sols, zones de travail et espaces communs entretenus." },
  { icon: Landmark, image: "administration.png", title: "Administrations", text: "Des bureaux et accueils nets pour vos équipes et visiteurs." },
  { icon: Cross, image: "clinic.png", title: "Cliniques & désinfection", text: "Hygiène renforcée des lieux d'accueil et surfaces de contact." },
  { icon: CalendarDays, image: "daily-cleaning.png", title: "Nettoyage quotidien", text: "Une prestation planifiée pour garder vos locaux impeccables." },
];

const standards = [
  { icon: ShieldCheck, number: "01", title: "Produits adaptés", text: "Nous sélectionnons les produits, machines et microfibres selon les matériaux présents : marbre, carrelage, parquet, inox, verre ou surfaces sensibles.", points: ["Surfaces respectées", "Hygiène maîtrisée"] },
  { icon: ClipboardCheck, number: "02", title: "Intervention organisée", text: "Avant de commencer, nous définissons les accès, les zones prioritaires, le déroulement et les horaires pour une prestation fluide, sans perturber votre activité.", points: ["Plan par zones", "Horaires adaptés"] },
  { icon: CheckCircle2, number: "03", title: "Contrôle de qualité", text: "Nos équipes vérifient les finitions, les détails visibles et les points de contact avant de clôturer la prestation avec vous.", points: ["Finitions vérifiées", "Résultat cohérent"] },
];

export default function Index() {
  return (
    <SiteShell>
      <PageHero eyebrow="Nettoyage professionnel à Alger" title="La propreté, au niveau de vos exigences." text="Zaki Cleaning intervient dans les sites professionnels, les logements, les écoles, les cliniques et après travaux avec une organisation rigoureuse." image="hero-airport.png" imagePosition="object-[74%_center] sm:object-center" />
      <TrustStrip />
      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="section-kicker">Nos domaines d'intervention</p><h2 className="section-title">Un service de nettoyage qui s'adapte à vos lieux.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-600">Maison occupée, villa, site administratif ou espace professionnel : nous organisons une prestation précise avec le matériel et la fréquence adaptés.</p></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, image, title, text }) => <article key={title} className="group overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_14px_40px_rgba(7,21,33,0.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_45px_rgba(7,21,33,0.14)]"><div className="h-52 overflow-hidden"><img src={imagePath(image)} alt={title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-6"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-sky-50 text-sky-600"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p><Link to="/services" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-sky-600 hover:text-sky-700">Voir le service <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div></div></section>
      <section className="bg-[#071521] text-white"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="min-h-[460px]"><img src={imagePath("daily-cleaning.png")} alt="Entretien quotidien par Zaki Cleaning" className="h-full w-full object-cover" /></div><div className="flex flex-col justify-center px-5 py-16 lg:px-16 lg:py-20"><p className="text-xs font-extrabold uppercase text-sky-300">Une méthode maîtrisée</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">Un résultat visible dans chaque zone.</h2><div className="mt-8 space-y-5">{[["Préparer", "Repérage des surfaces, accès et priorités avant l'intervention."],["Nettoyer", "Matériel professionnel et méthode adaptée à chaque type de lieu."],["Vérifier", "Contrôle des finitions avant validation avec le client."]].map(([title, text], index) => <div key={title} className="flex gap-4 border-t border-white/15 pt-5"><span className="text-sm font-extrabold text-sky-300">0{index + 1}</span><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-300">{text}</p></div></div>)}</div></div></div></section>
      <section className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="section-kicker">Notre engagement</p><WordPullUp words="Une qualité visible, du premier geste au dernier contrôle." className="mt-4 text-3xl font-extrabold leading-tight text-slate-950 sm:text-5xl" /></div><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Une prestation professionnelle ne se résume pas à nettoyer. Elle protège vos surfaces, respecte votre rythme et laisse un lieu vraiment prêt à être utilisé.</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{standards.map(({ icon: Icon, number, title, text, points }) => <article key={title} className="group rounded-lg border border-slate-200 bg-white p-7 shadow-[0_14px_38px_rgba(7,21,33,0.07)] transition duration-300 hover:-translate-y-1 hover:border-sky-300 hover:shadow-[0_20px_44px_rgba(7,21,33,0.12)]"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-sky-50 text-sky-600"><Icon className="h-6 w-6" /></span><span className="text-sm font-extrabold text-slate-300">{number}</span></div><h3 className="mt-8 text-2xl font-extrabold text-slate-950">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p><div className="mt-6 flex flex-wrap gap-2">{points.map((point) => <span key={point} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">{point}</span>)}</div></article>)}</div></div></section>
      <CtaBand />
    </SiteShell>
  );
}
